name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.110.0"
          extended: true

      - name: Build
        run: 'hugo'
     
      - name: Sync Files
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.SERVER_HOST }}
          remote-user: ${{ secrets.SERVER_USERNAME }}
          private-ssh-key: ${{ secrets.SERVER_SSH_KEY }}
          source-path: ./public/
          destination-path: ~/public_html/tutorials-share/
